Update dependabot-auto-merge.yml

diff --git a/.github/workflows/dependabot-auto-merge.yml b/.github/workflows/dependabot-auto-merge.yml
--- a/.github/workflows/dependabot-auto-merge.yml
+++ b/.github/workflows/dependabot-auto-merge.yml
@@ -1,27 +1,71 @@
-# Automatically merge Dependabot PRs when version comparison is within the range
-# that is configured in .github/auto-merge.yml
-
-name: Auto-Merge Dependabot PRs
+name: Dependabot auto-merge
+on: pull_request
 
 permissions:
-    contents: read
-    pull-requests: write
-
-on:
-    # WARNING: This needs to be run in the PR base, DO NOT build untrusted code in this action
-    # details under https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
-    pull_request_target:
+  contents: write
+  pull-requests: write
+  checks: read
+  actions: read
+  statuses: read
 
 jobs:
-    auto-merge:
-        if: github.actor == 'dependabot[bot]'
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@v4
+  dependabot:
+    runs-on: ubuntu-latest
+    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'eifel-tech/ioBroker.syrconnect'
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      PR_URL: ${{github.event.pull_request.html_url}}
+    steps:
+     - name: Checkout
+       uses: actions/checkout@v4
+       with:
+          fetch-depth: 0
+     - name: SetUp auto-merge
+       id: auto-merge
+       uses: dependabot/fetch-metadata@v2.2.0
+       with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+     - name: Wait 5 minutes for other checks to complete
+       run: sleep 300
+     - name: Check if all workflows have passed
+       run: |
+          MAX_RETRIES=6
+          RETRY_INTERVAL=300  # Specify 5 minutes in seconds
+          ATTEMPT=0
+          CURRENT_WORKFLOW="Dependabot auto-merge"
 
-            - name: Check if PR should be auto-merged
-              uses: ahmadnassri/action-dependabot-auto-merge@v2
-              with:
-                  github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
-                  command: squash and merge
+          while [ $ATTEMPT -lt $MAX_RETRIES ]; do
+            echo "Fetching PR status checks..."
+            WORKFLOWS=$(gh pr view "$PR_URL" --json statusCheckRollup -q '.statusCheckRollup')
+
+            # Debug: Output the status of all checks
+            echo "Debug: Current status of all checks:"
+            WORKFLOW_STATUS=$(jq -r '[.[] | {name: (.workflowName // .name // .context), type: .["__typename"], status: .status, state: .state, conclusion: .conclusion}]' <<< "$WORKFLOWS")
+
+            # Check if all checks except the current workflow have succeeded
+            all_passed=true
+            while IFS= read -r check; do
+              name=$(jq -r '.name' <<< "$check")
+              type=$(jq -r '.type' <<< "$check")
+              status=$(jq -r 'if .type == "CheckRun" then .conclusion else .state end' <<< "$check")
+              if [[ "$name" != "$CURRENT_WORKFLOW" && "$status" == "FAILED" ]]; then
+                all_passed=false
+                echo "Failed check: $name ($type) - Status: $status"
+                break
+              fi
+            done < <(echo "$WORKFLOW_STATUS" | jq -c '.[]')
+
+            if $all_passed; then
+              echo "All other checks have passed"
+              exit 0
+            else
+              echo "Some status checks have not passed. Attempt $((ATTEMPT + 1)) of $MAX_RETRIES."
+              echo "Retrying in $RETRY_INTERVAL seconds..."
+              sleep $RETRY_INTERVAL
+              ATTEMPT=$((ATTEMPT + 1))
+            fi
+          done
+          echo "Failed to merge the PR after $MAX_RETRIES attempts due to failing status checks."
+          exit 1
+     - name: Auto-merge for Dependabot PRs
+       run: gh pr merge --auto --merge "$PR_URL"
